# Generated by Django 4.0.1 on 2022-03-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_report_sent',
            field=models.DateField(null=True),
        ),
    ]
